### ISSUE TITLE
mbox shared certs

### ISSUE THREAD

**Issue by odra** [fedora-infra/mbbox#57]
parent issue: #33 

As an user, I want to manage my shared certificates from the mbox crd. 

## Acceptance criteria

* Create a self signed CA secret if not present (see notes section for secret format);
* Create a secret that contains a server/httpd certificate using the shared CA secret from the previous step if not present  (see notes section for secret format);
* Mbox CRD should have two fields to reference both secrets names. 

## Definition of Done

Being able to manage shared mbox TSL  CAs, certificates and private keys in the operator.

### CA Secret

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: service-ca
  labels:
    app: identity
data:
  cert: fillme
```

### Service (HTTPD) Secret

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: service-cert
  labels:
    app: identity
data:
  tls.crt: fillme
  tls.key: fillme
```
