### ISSUE TITLE
mbox shared pvs

### ISSUE THREAD

**Issue by odra** [fedora-infra/mbbox#58]
parent issue: #33 

As an user, I want to manage my shared PVs (persistent volumes) from the mbox crd. 

## Acceptance criteria

* Create a shared koji PVC that will be used by both koji-hub and koji-builder if not present;
* Wait for PVC readiness;
* Both size and storage backend/config should be configurable;
* Default values for size and backjend type/config.

## Definition of Done

Being able to manage koji's shared volume in the operator.

### PVC Definition

Sample PVC resource:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ pvc_name }}
  labels:
    app: koji
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ pvc_size }}
  selector:
    matchLabels:
      app: "koji"

```
